# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2016

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        ref: master

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      shell: bash
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        mkdir ./Build
        mkdir ./Build/Release
        cp "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\winuser.h" ./Build/Release/
        cd ./Build/Release
        7z a -r -ssw -mx5 -t7z test.7z
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifact
        path: ./build/Release/test.7z
